name: Auto-update index.html

on:
  push:
    branches:
      - main
    paths:
      - '*.html'

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update index.html with new links
      run: |
        # Get all the HTML files except index.html
        files=$(find . -type f -name "*.html" ! -name "index.html")
        
        # Create the new content for index.html
        echo "<!DOCTYPE html>" > index.html
        echo "<html lang=\"en\">" >> index.html
        echo "<head><meta charset=\"UTF-8\"><title>Vocab de Cody</title></head>" >> index.html
        echo "<body>" >> index.html
        echo "<h1>Vocab de Cody</h1>" >> index.html
        echo "<ul>" >> index.html
        
        for file in $files; do
          # Add a link for each file
          echo "<li><a href=\"$file\">$(basename $file)</a></li>" >> index.html
        done
        
        echo "</ul>" >> index.html
        echo "</body></html>" >> index.html

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add index.html
        git commit -m "Auto-update index.html with new HTML files"
        git push
