name: Auto Update Index

on:
  push:
    branches:
      - main

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate index.html
        run: |
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Vocab de Cody</title>
          </head>
          <body>
              <h1>Vocab de Cody</h1>
              <p>Click a link below to open an HTML file:</p>
              <ul>' > index.html

          for file in *.html; do
            if [[ "$file" != "index.html" ]]; then
              echo "              <li><a href=\"$file\">$file</a></li>" >> index.html
            fi
          done

          echo '              </ul>
          </body>
          </html>' >> index.html

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add index.html
          git commit -m "Auto-update index.html"
          git push


